[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[project]
name = "sicritfix"
version = "0.0.7"
description = "Python package to detect and correct oscillatory artifacts in mass spectrometry mzML data."
readme = "README.md"
requires-python = ">=3.11,<3.12"
dynamic = ["classifiers"]
license = "GPL-3.0-only"

authors = [
    { name = "Maite Gómez del Rio Vinuesa", email = "maite.gomezriovinuesa@gmail.com" },
    { name = "Alberto Gil de la Fuente", email = "alberto.gilf@gmail.com" },
    { name = "Víctor González Ruíz", email = "vgonzalezruiz@gmail.com" }
]
maintainers = [
    { name = "Maite Gómez del Rio Vinuesa", email = "maite.gomezriovinuesa@gmail.com" },
    { name = "Alberto Gil de la Fuente", email = "alberto.gilf@gmail.com" }
]

keywords = [
    "mass spectrometry",
    "mzML",
    "signal correction",
    "fft",
    "phase",
    "oscillations"
]

dependencies = [
    "numpy>=2.0,<3.0",
    "scipy>=1.13",
    "pandas",
    "pyopenms"
]

scripts = { sicritfix = "sicritfix.cli:main" }


[project.urls]
Homepage = "https://github.com/ceu-biolab/Oscillations_Corrector_Algorithm_SICRIT"
Repository = "https://github.com/ceu-biolab/Oscillations_Corrector_Algorithm_SICRIT"
Documentation = "https://github.com/ceu-biolab/Oscillations_Corrector_Algorithm_SICRIT#readme"


[tool.poetry]
classifiers = [
    "Development Status :: 3 - Alpha",
    "Intended Audience :: Science/Research",
    "Programming Language :: Python :: 3.11",
    "Operating System :: OS Independent",
    "Topic :: Scientific/Engineering :: Bio-Informatics"
]

packages = [
    { include = "sicritfix", from = "sicritfix-project/src" }
]

[dependencies]
python = "^3.11"
numpy = ">=2.0,<3.0"
scipy = ">=1.13"
pandas = "*"
pyopenms = "*"

[tool.poetry.group.dev.dependencies]
pytest = "^7.0"


